version: '3.5'

services:

  filewalkerd:
    image: lumue/filewalkerd:latest
    restart: always
    ports:
      - "8020:8002"
    volumes:
      - type: volume
        source: media
        target: /media
        volume:
          nocopy: true
    environment:
      - LANG=C.UTF-8
      - JAVA_OPTS="-Dfile.encoding=UTF-8"

volumes:
  media:
    driver_opts:
      type: "nfs4"
      o: "addr=10.108.5.6,nolock,soft,rw"
      device: ":/mnt/pool_hdd/media"

